const ADD_SUCCESS = 'menu/ADD_SUCCESS';
const DELETE_SUCCESS = 'menu/DELETE_SUCCESS';
const TOGGLE_COMPLETED_SUCCESS = 'menu/TOGGLE_COMPLETED_SUCCESS';
const CHANGE_FILTER = 'menu/CHANGE_FILTER';

const FETCH_REQUEST = 'menu/FETCH_REQUEST';
const FETCH_SUCCESS = 'menu/FETCH_SUCCESS';
const FETCH_ERROR = 'menu/FETCH_ERROR';

export {
  ADD_SUCCESS,
  DELETE_SUCCESS,
  TOGGLE_COMPLETED_SUCCESS,
  CHANGE_FILTER,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
};
